version: "3.8"
services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=devpe
      volumes:
          - postgres:/var/lib/postgresql
      ports:
          - "5432:5432"
volumes:
   postgres:
